server:
  port: 8080
spring:
  application:
    name: houtai
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/company_frame?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: mysql
      ################## 连接池配置 ################
      initial-size: 5  #连接池建立时创建的初始化连接数
      max-active: 20   #连接池中最大的活跃连接数
      min-idle: 5      #连接池中最小的活跃连接数
      max-wait: 5      # 配置获取连接等待超时的时间
      pool-prepared-statements: true  # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false   #是否在获得连接后检测其可用性
      test-on-return: false   #是否在连接放回连接池后检测其可用性
      test-while-idle: true   #是否在连接空闲一段时间后检测其可用性
      time-between-eviction-runs-millis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
      filters: stat,wall                          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  #resources:
  #  static-locations: classpath:/static/ ,classpath:/templates/

  #thymeleaf
  thymeleaf:
    # 前缀 默认读取 classpath:/templates/
    prefix: classpath:/templates/
    # 后缀
    suffix: .html
    charset: UTF-8
    servlet:
      content-type: text/html
      # 缓存
    cache: false
mybatis:
  # 配置多个 type-aliases-package
  type-aliases-package: com.study.houtai.po
  #加入以下配置 对应生成 mapper.xml 的路径
  mapper-locations: classpath:mapper/*.xml



